/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'brew' at '12/14/15 9:37 AM' with Gradle 2.9
 *
 * @author brew, @date 12/14/15 9:37 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
